### ISSUE TITLE
Create the first draft of READ-Only operations for Proposal Making

### ISSUE THREAD

**Issue by cdparra** [jackieg017/AppCivist-Proposal-Making#1]
Think about what are the main read-only operations needed to support the proposal making capability and create a shortlist in a gdoc or a marckdown wiki page in the repository

**Comment by jackieg017** [comment]
1. issueTitle(String name)
2. addQuestion(String name)
3. addSuggestion(String name)
4. proposalTitle(String name)
5. memberNameToTag(String name)
6. enterContext( ??); // Using Scanner? Using Buffer? Maybe too specific?
7. addCondition(String condition?);
